### PR TITLE
Fixing 404 page | Adding copyright 

### PR DESCRIPTION
**Pull request by kerrtravers**
## About
- Fixes the 404 page
- Adds your copyright

### CODE REVIEW

**Comment by DeleteThisAcount** [comment]
The 404 page is already sorta working.
I did the copyright already before your did this pull request.

**Comment by kerrtravers** [comment]
Ah, I resolved the conflict. The bit I added to the 404 page makes it more reliable, So I would keep it.

Ps - Nice easter egg :P

**Comment by DeleteThisAcount** [comment]
Thanks :P

**Comment by kerrtravers** [comment]
No Problem!

party

**Comment by DeleteThisAcount** [comment]
😀

**Comment by DeleteThisAcount** [comment]
need help... the css on the 404 page is now gone???

**Comment by DeleteThisAcount** [comment]
never mind. i removed the thing at the top and it fixed it self... weird

**Comment by kerrtravers** [comment]
@deletethisaccount hmmm

**Pull request merged**
